name: "Varios Jobs"

on:
  push:
    branches: ["master"]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Hola
        run: echo "Hola, este es el primer job del workflow."
      - name: touch file
        run: touch hola.txt
      - name: Set text
        run: echo "Hola, este es el primer job del workflow." > hola.txt
      - name: cat file
        run: cat hola.txt

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: actions/checkout@v4
      - name: LS
        run: ls -al
